blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/jsattler/BetterCapture/discussions/categories/ideas
    about: Please open a discussion before requesting a feature. Issues and pull requests for feature requests submitted without prior discussion will be closed immediately.
  - name: Questions & Help
    url: https://github.com/jsattler/BetterCapture/discussions/categories/q-a
    about: Ask questions and get help from the community.
